include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ lib/model/entity/env.dart, lib/**.g.dart ]

linter:
  rules:
    - prefer_single_quotes
    - prefer_relative_imports
    - require_trailing_commas
