name: one_moon
description: "Planner for Anxious People"
version: 1.7.2+30

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.0
  table_calendar: ^3.1.2
  json_annotation: ^4.9.0
  path: ^1.9.0
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  encrypt: ^5.0.3
  envied: ^0.5.4+1
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.7.0
  googleapis: ^13.2.0
  google_sign_in: ^6.2.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  http: ^1.2.2
  upgrader: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
  generate: true
