name: one_moon
description: "Planner for Anxious People"
version: 1.2.1+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.0
  table_calendar: ^3.1.2
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
