// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'env/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace with own options from own project
  static FirebaseOptions android = FirebaseOptions(
    apiKey: Env.androidApiKey,
    appId: '1:369328720460:android:f32bfa8a8503b5024302e9',
    messagingSenderId: '369328720460',
    projectId: 'one-moon-1563d',
    storageBucket: 'one-moon-1563d.firebasestorage.app',
  );

  // Replace with your own options from own project
  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.iosApiKey,
    appId: '1:369328720460:ios:60bd4ac2483721cf4302e9',
    messagingSenderId: '369328720460',
    projectId: 'one-moon-1563d',
    storageBucket: 'one-moon-1563d.firebasestorage.app',
    iosBundleId: 'com.ios.oneMoon',
  );
}
