name: build

on:
  pull_request:
    branches:
      - 'dependabot/**'
  push:
    branches:
      - 'dependabot/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '20'

      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: refresh flutter packages
        run: flutter clean && flutter pub get

      - name: Create .env file with GitHub Secrets
        run: |
          echo "ENCRYPT_KEY=$ENCRYPT_KEY" > .env
          echo "ENCRYPT_IV=$ENCRYPT_IV" >> .env
          echo "ANDROID_API_KEY=$ANDROID_API_KEY" >> .env
          echo "IOS_API_KEY=$IOS_API_KEY" >> .env

      - name: Generate env built file
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: build ios app with flutter
        run: flutter build ios --no-codesign

      - name: android app with flutter
        run: flutter build appbundle --debug
