name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: refresh flutter packages
        run: flutter clean && flutter pub get

      - name: Create .env file with GitHub Secrets
        run: |
          echo "ENCRYPT_KEY=$ENCRYPT_KEY" > .env
          echo "ENCRYPT_IV=$ENCRYPT_IV" >> .env
          echo "ANDROID_API_KEY=$ANDROID_API_KEY" >> .env
          echo "IOS_API_KEY=$IOS_API_KEY" >> .env

      - name: Generate env built file
        run: dart run build_runner build --delete-conflicting-outputs

      - name: run flutter analyzer
        run: flutter analyze
